server:
    port: 8081
spring:
    security:
      oauth2:
          resourceserver:
            jwt:
              issuer-uri: https://dev-54918101.okta.com/oauth2/default

          client:
            registration:
              my-internal-client:
                provider: okta
                authorizationGrantType: client_credentials
                client-id: 0oa9qndvrxpHgmVPB5d7
                client-secret: ikLNqBrG-zOwwbza20Vj8UwXYI43Z8106YCHvzLz
                scopes: openid, profile, email, offline_access

            provider:
              okta:
                issuerUri: https://dev-54918101.okta.com/oauth2/default



    config:
        import: optional:configserver:http://localhost:8888
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        password: secret
        url: jdbc:mysql://localhost:3306/microservices
        username: appuser
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
    profiles:
        active: user-service-local
management:
    endpoint:
        health:
            enabled: true
            show-details: always
    endpoints:
        enabled-by-default: false
        web:
            exposure:
                include: '*'
    health:
      circuitbreakers:
        enabled: true
resilience4j:
    circuitbreaker:
        instances:
            ratingHotelBreaker:
                registerHealthIndicator: true
                eventConsumerBufferSize: 10
                failureRateThreshold: 50
                minimumNumberOfCalls: 5
                automaticTransitionFromOpenToHalfOpenEnabled: true
                waitDurationInOpenState: 6s
                permittedNumberOfCallsInHalfOpenState: 3
                slidingWindowSize: 10
                slidingWindowType: COUNT_BASED
    retry:
      instances:
          ratingHotelBreaker:
              maxAttempts: 3
              waitDuration: 3s
    ratelimiter:
        instances:
          userRateLimiter:
              limitRefreshPeriod: 5s
              limitForPeriod: 1
              timeoutDuration: 0s

okta:
  oauth2:
    issuer: https://dev-54918101.okta.com/oauth2/default
    audience: api://default