server:
    port: 8081
spring:
    config:
        import: optional:configserver:http://localhost:8888
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        password: secret
        url: jdbc:mysql://localhost:3306/microservices
        username: appuser
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
    profiles:
        active: user-service-local
management:
    endpoint:
        health:
            enabled: true
            show-details: always
    endpoints:
        enabled-by-default: false
        web:
            exposure:
                include: '*'
    health:
      circuitbreakers:
        enabled: true
resilience4j:
    circuitbreaker:
        instances:
            ratingHotelBreaker:
                registerHealthIndicator: true
                eventConsumerBufferSize: 10
                failureRateThreshold: 50
                minimumNumberOfCalls: 5
                automaticTransitionFromOpenToHalfOpenEnabled: true
                waitDurationInOpenState: 6s
                permittedNumberOfCallsInHalfOpenState: 3
                slidingWindowSize: 10
                slidingWindowType: COUNT_BASED
    retry:
      instances:
          ratingHotelBreaker:
              maxAttempts: 3
              waitDuration: 3s
    ratelimiter:
        instances:
          userRateLimiter:
              limitRefreshPeriod: 5s
              limitForPeriod: 1
              timeoutDuration: 0s