server:
  port: 8082

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/microservice
    username: postgres
    password: secret
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  rsocket:
    server:
  config:
    import: optional:configserver:http://localhost:8888
  profiles:
    active: hotel-service

management:
  endpoints:
    web:
      exposure:
        include: "*"
