server:
  port: 8082

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/microservice
    username: postgres
    password: secret
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  rsocket:
    server:
  config:
    import: optional:configserver:http://localhost:8888
  profiles:
    active: hotel-service

#management:
#  endpoints:
#    web:
#      exposure:
#        include: "*"
management:
  endpoint:
    health:
      enabled: true
      show-details: always
  endpoints:
    enabled-by-default: false
    web:
      exposure:
        include: "*"

okta:
  oauth2:
    issuer: https://dev-54918101.okta.com/oauth2/default
    audience: api://default